##Generate File for Python Script from Segmentation File##

setwd("/Users/arndtlab/Desktop/MAE/TilingArrayQuantileNormalizedData_3-10-17/tilingArray")
dir()

m1=cbind(attributes(tilingData$"1.-")$x, attributes(tilingData$"1.-")$y)
m2=cbind(attributes(tilingData$"2.-")$x, attributes(tilingData$"2.-")$y)
m3=cbind(attributes(tilingData$"3.-")$x, attributes(tilingData$"3.-")$y)
m4=cbind(attributes(tilingData$"4.-")$x, attributes(tilingData$"4.-")$y)
m5=cbind(attributes(tilingData$"5.-")$x, attributes(tilingData$"5.-")$y)
m6=cbind(attributes(tilingData$"6.-")$x, attributes(tilingData$"6.-")$y)
m7=cbind(attributes(tilingData$"7.-")$x, attributes(tilingData$"7.-")$y)
m8=cbind(attributes(tilingData$"8.-")$x, attributes(tilingData$"8.-")$y)
m9=cbind(attributes(tilingData$"9.-")$x, attributes(tilingData$"9.-")$y)
m10=cbind(attributes(tilingData$"10.-")$x, attributes(tilingData$"10.-")$y)
m11=cbind(attributes(tilingData$"11.-")$x, attributes(tilingData$"11.-")$y)
m12=cbind(attributes(tilingData$"12.-")$x, attributes(tilingData$"12.-")$y)
m13=cbind(attributes(tilingData$"13.-")$x, attributes(tilingData$"13.-")$y)
m14=cbind(attributes(tilingData$"14.-")$x, attributes(tilingData$"14.-")$y)
m15=cbind(attributes(tilingData$"15.-")$x, attributes(tilingData$"15.-")$y)
m16=cbind(attributes(tilingData$"16.-")$x, attributes(tilingData$"16.-")$y)
m17=cbind(attributes(tilingData$"17.-")$x, attributes(tilingData$"17.-")$y)

colnames(m1)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m2)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m3)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m4)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m5)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m6)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m7)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m8)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m9)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m10)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m11)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m12)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m13)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m14)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m15)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m16)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(m17)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")

p1=cbind(attributes(tilingData$"1.-")$x, attributes(tilingData$"1.-")$y)
p2=cbind(attributes(tilingData$"2.-")$x, attributes(tilingData$"2.-")$y)
p3=cbind(attributes(tilingData$"3.-")$x, attributes(tilingData$"3.-")$y)
p4=cbind(attributes(tilingData$"4.-")$x, attributes(tilingData$"4.-")$y)
p5=cbind(attributes(tilingData$"5.-")$x, attributes(tilingData$"5.-")$y)
p6=cbind(attributes(tilingData$"6.-")$x, attributes(tilingData$"6.-")$y)
p7=cbind(attributes(tilingData$"7.-")$x, attributes(tilingData$"7.-")$y)
p8=cbind(attributes(tilingData$"8.-")$x, attributes(tilingData$"8.-")$y)
p9=cbind(attributes(tilingData$"9.-")$x, attributes(tilingData$"9.-")$y)
p10=cbind(attributes(tilingData$"10.-")$x, attributes(tilingData$"10.-")$y)
p11=cbind(attributes(tilingData$"11.-")$x, attributes(tilingData$"11.-")$y)
p12=cbind(attributes(tilingData$"12.-")$x, attributes(tilingData$"12.-")$y)
p13=cbind(attributes(tilingData$"13.-")$x, attributes(tilingData$"13.-")$y)
p14=cbind(attributes(tilingData$"14.-")$x, attributes(tilingData$"14.-")$y)
p15=cbind(attributes(tilingData$"15.-")$x, attributes(tilingData$"15.-")$y)
p16=cbind(attributes(tilingData$"16.-")$x, attributes(tilingData$"16.-")$y)
p17=cbind(attributes(tilingData$"17.-")$x, attributes(tilingData$"17.-")$y)

colnames(p1)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p2)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p3)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p4)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p5)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p6)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p7)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p8)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p9)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p10)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p11)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p12)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p13)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p14)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p15)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p16)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")
colnames(p17)=c("x", "Paf1_1", "Paf1_2", "Paf1_3", "Trf_Paf1_1", "Trf_Paf1_2", "Trf_Paf1_3", "Trf_1", "Trf_2", "Trf_3", "Wild_1", "Wild_2", "Wild_3")


setwd("/Users/arndtlab/Desktop/MAE/TilingArrayQuantileNormalizedData_3-10-17/filesForPython")
dir()

write.table(m1, "1.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m2, "2.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m3, "3.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m4, "4.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m5, "5.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m6, "6.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m7, "7.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m8, "8.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m9, "9.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m10, "10.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m11, "11.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m12, "12.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m13, "13.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m14, "14.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m15, "15.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m16, "16.-.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(m17, "17.-.csv", sep=",", quote=F, col.names=T, row.names=T)


write.table(p1, "1.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p2, "2.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p3, "3.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p4, "4.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p5, "5.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p6, "6.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p7, "7.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p8, "8.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p9, "9.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p10, "10.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p11, "11.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p12, "12.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p13, "13.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p14, "14.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p15, "15.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p16, "16.+.csv", sep=",", quote=F, col.names=T, row.names=T)
write.table(p17, "17.+.csv", sep=",", quote=F, col.names=T, row.names=T)

